version: '3.7'
services:
  # data-generator:
  #   build: ./data-generator
  #   container_name: data-generator
  #   depends_on:
  #     redpanda: { condition: service_healthy }
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda
    container_name: redpanda
    command:
     - redpanda start
     - --overprovisioned
     - --smp 1
     - --memory 1G
     - --reserve-memory 0M
     - --node-id 0
     - --check=false
     - --kafka-addr 0.0.0.0:9092
     - --advertise-kafka-addr redpanda:9092
     - --pandaproxy-addr 0.0.0.0:8082
     - --advertise-pandaproxy-addr redpanda:8082
     - --set redpanda.enable_transactions=true
     - --set redpanda.enable_idempotence=true
     - --set redpanda.auto_create_topics_enabled=true
    ports:
      - "9092:9092"
      - "8082:8082"
    healthcheck: { test: curl -f localhost:9644/v1/status/ready, interval: 1s, start_period: 30s }
  materialized:
    image: materialize/materialized
    container_name: materialized
    #command: -w1
    ports:
      - "6875:6875"
  mzcli:
    image: materialize/cli
    container_name: mzcli
  dbt:
    build:
      context: ./dbt
      target: dbt-third-party
      args:
        - build_for=${ARCH}
    container_name: dbt
    ports:
      - "8000:8080"
    volumes:
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
      - ./dbt/:/usr/app/dbt
    stdin_open: true
    tty: true
    depends_on:
      - materialized
  metabase:
    image: ${MIMG}/metabase
    container_name: metabase
    depends_on:
      - materialized
    ports:
      - "3030:3000"

  debezium:
    build: .
    image: custom-connect:2.2.1
    depends_on:
      - redpanda
      - schema-registry
      - mysql
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=redpanda:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=inventory.configs
      - OFFSET_STORAGE_TOPIC=inventory.offset
      - STATUS_STORAGE_TOPIC=inventory.status
      - INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.3
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=redpanda:9092
      - SCHEMA_REGISTRY_DEBUG=true
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
    ports:
     - 8181:8181
     - 8081:8081
    depends_on:
      - redpanda
  mysql:
    image: debezium/example-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw