# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'debezium_redpanda_dbt_materialize'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'debezium_redpanda_dbt_materialize'

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

models:
  examples:
    +enabled: true
    
  templates:
    +enabled: false

dispatch:
  - macro_namespace: dbt_utils
    search_order: [materialize_dbt_utils, dbt_utils]
  - macro_namespace: audit_helper
    search_order: [materialize_dbt_utils, audit_helper]
vars:
  db: "testDB"
  dbsrv: "server1"